//! QuantLib parity fixtures. Spec: `TESTING_STRATEGY.md §3.1`.
//!
//! These fixtures are committed under `tests/fixtures/quantlib.json`. The
//! starter set contains only asymptotic-limit cases (P_no_touch → 0) — those
//! are structurally robust under any reasonable Hui implementation, so they
//! function as smoke tests, not as a tight parity gate. The pre-launch
//! verification §6.1 requires 100 randomized cases generated by
//! `games/tap-trading/scripts/gen-quantlib-fixtures.py` against the real
//! QuantLib reference; until then this file cannot satisfy the spec's <1%
//! relative error gate.

use serde::Deserialize;
use tap_trading_pricing_engine::{
    constants::SECONDS_PER_YEAR, first_passage_touch_prob, hui_no_touch,
};

#[derive(Debug, Deserialize)]
struct Fixture {
    spot: f64,
    l: f64,
    h: f64,
    sigma_annualized: f64,
    tau_sec: f64,
    expected_p_no_touch: f64,
}

fn load_fixtures() -> Vec<Fixture> {
    let raw = include_str!("fixtures/quantlib.json");
    serde_json::from_str(raw).expect("quantlib.json must parse")
}

/// Out-of-band single-barrier touch fixture: spot starts on one side of a
/// near barrier and the cell wins by first passage to it.
#[derive(Debug, Deserialize)]
struct OneTouchFixture {
    spot: f64,
    barrier: f64,
    sigma_annualized: f64,
    tau_sec: f64,
    expected_p_touch: f64,
}

fn load_one_touch_fixtures() -> Vec<OneTouchFixture> {
    let raw = include_str!("fixtures/quantlib_onetouch.json");
    serde_json::from_str(raw).expect("quantlib_onetouch.json must parse")
}

#[test]
fn hui_parity_within_tolerance() {
    let fixtures = load_fixtures();
    assert!(!fixtures.is_empty(), "fixture file is empty");

    // Tight gate per spec §6.1: 1% relative OR 1e-3 absolute. The previous
    // `abs_err < 0.01` fallback accepted 1-percentage-point drift on the
    // [0, 1] probability scale, which made near-zero fixtures vacuous.
    // After `gen-quantlib-fixtures.py` produces 100 non-limit cases, the
    // relative branch becomes the binding constraint.
    let rel_tolerance = 0.01;
    let abs_tolerance = 1e-3;

    for (idx, f) in fixtures.iter().enumerate() {
        let sigma_per_sec = f.sigma_annualized / SECONDS_PER_YEAR.sqrt();
        let got = hui_no_touch(f.spot, f.l, f.h, sigma_per_sec, f.tau_sec, 10)
            .expect("fixture inputs must be valid");

        let abs_err = (got - f.expected_p_no_touch).abs();
        let rel_err = if f.expected_p_no_touch.abs() > abs_tolerance {
            abs_err / f.expected_p_no_touch.abs()
        } else {
            f64::INFINITY
        };

        assert!(
            rel_err < rel_tolerance || abs_err < abs_tolerance,
            "fixture {idx}: got {got}, expected {} (abs_err={abs_err}, rel_err={rel_err})",
            f.expected_p_no_touch
        );
    }
}

/// Parity gate for the production OTM path — `first_passage_touch_prob`, the
/// formula that actually prices high-multiplier cells (the in-band Hui gate
/// above verifies a function `compute_p_touch` never calls).
///
/// The engine uses the reflection approximation `2·Φ(−b/v)`, which drops the
/// −σ²/2 log-drift; measured worst case vs QuantLib is ~0.24% relative /
/// 2.2e-4 absolute across the fixture corpus. The 1% rel / 1e-3 abs gate
/// passes that legitimate approximation error while catching a dropped `2·`,
/// a mis-scaled `v`, or a sign flip — each of which blows past 1%.
#[test]
fn otm_quantlib_parity() {
    let fixtures = load_one_touch_fixtures();
    assert!(!fixtures.is_empty(), "one-touch fixture file is empty");

    let rel_tolerance = 0.01;
    let abs_tolerance = 1e-3;

    for (idx, f) in fixtures.iter().enumerate() {
        let sigma_per_sec = f.sigma_annualized / SECONDS_PER_YEAR.sqrt();
        let got = first_passage_touch_prob(f.spot, f.barrier, sigma_per_sec, f.tau_sec);

        let abs_err = (got - f.expected_p_touch).abs();
        let rel_err = if f.expected_p_touch.abs() > abs_tolerance {
            abs_err / f.expected_p_touch.abs()
        } else {
            f64::INFINITY
        };

        assert!(
            rel_err < rel_tolerance || abs_err < abs_tolerance,
            "one-touch fixture {idx}: got {got}, expected {} (abs_err={abs_err}, rel_err={rel_err})",
            f.expected_p_touch
        );
    }
}
