#!/usr/bin/env bash
# init-worktree-dev.sh — one-command bootstrap for local dev in this worktree.
# Mandatory entry point: nothing else (mprocs, headless, raw `bun dev`) should
# run before this.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# 1) Compute worktree-isolated env (ports, compose project name).
# shellcheck source=worktree-env.sh
source "$SCRIPT_DIR/worktree-env.sh"

# 2) Ensure per-worktree state directories exist.
mkdir -p "$REPO_ROOT/.local" "$REPO_ROOT/.local/redis-data" "$REPO_ROOT/tmp" "$REPO_ROOT/tmp/pids"

# 3) (Re)generate the canonical .env from worktree-env.sh. Always rewrite, not
# "create if missing": rewriting every run is what lets new vars and corrected
# values (e.g. a changed WS path) reach worktrees created before they were
# added, instead of wedging the coherence check below. Existing file is backed
# up to .env.bak so a hand-added key is never lost silently. Atomic write.
canonical_env="$REPO_ROOT/.local/.env"
if [[ -f "$canonical_env" ]]; then
  cp "$canonical_env" "$canonical_env.bak"
fi
tmpfile="$(mktemp)"
cat >"$tmpfile" <<EOF
# Canonical per-worktree environment. Generated by scripts/init-worktree-dev.sh.
# Service-specific .env.local files are derived from this via sync-service-envs.sh.

PLATFORM_DB_PORT=${PLATFORM_DB_PORT}
PLATFORM_REDIS_PORT=${PLATFORM_REDIS_PORT}
TAP_UI_PORT=${TAP_UI_PORT}
TAP_API_PORT=${TAP_API_PORT}
TAP_AGGREGATOR_PORT=${TAP_AGGREGATOR_PORT}
TAP_WORKER_METRICS_PORT=${TAP_WORKER_METRICS_PORT}

PLATFORM_DB_URL=${PLATFORM_DB_URL}
PLATFORM_REDIS_URL=${PLATFORM_REDIS_URL}
TAP_UI_URL=${TAP_UI_URL}
TAP_API_URL=${TAP_API_URL}
TAP_AGGREGATOR_WS_URL=${TAP_AGGREGATOR_WS_URL}
TAP_DB_URL=${TAP_DB_URL}

COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}

# Logging
RUST_LOG=info,tower_http=debug
EOF
mv "$tmpfile" "$canonical_env"
echo "[init] (re)generated $canonical_env from worktree-env.sh"

# 4) Validate coherence — hard stop on any mismatch.
"$SCRIPT_DIR/ensure-worktree-coherence.sh"

# 5) Propagate canonical env to service-specific .env.local files.
"$SCRIPT_DIR/sync-service-envs.sh"

# 6) Bring up Postgres + Redis and apply Tick migrations via the migrate crate
# (picks up PLATFORM_DB_URL from the env exported above).
docker compose up -d postgres redis >/dev/null
echo "[init] waiting for postgres to be ready..."
until docker compose exec -T postgres pg_isready -U dopamint -d dopamint -q 2>/dev/null; do
  sleep 0.5
done

cargo run -p tap-trading-migrate \
  --manifest-path games/tap-trading/backend/Cargo.toml -q -- run
echo "[init] migrations applied"

# 7) Print summary.
cat <<EOF

[init] worktree dev env ready

  repo root        $REPO_ROOT
  port offset      $DOPAMINT_PORT_OFFSET
  tap-api          $TAP_API_URL
  tap-ui           $TAP_UI_URL
  compose project  $COMPOSE_PROJECT_NAME

next:
  interactive  -> mprocs --config mprocs.yaml
  headless     -> ./scripts/start-headless.sh
EOF
